### ISSUE TITLE
Scripts cannot be used from repository

### ISSUE THREAD

**Issue by knghtbrd** [RasppleII/a2server#1]
(For completeness)

Presently these scripts can only be used if they are first installed as a current release on @IvanExpert's ivanx.cim website. This prevents you from running the full script suite start to finish in the course of testing a future release, or from really testing the primary script. It also limits development to primarily Ivan without plans for a full and complete fork.

Solution discussed is to create a variable that, if defined, will allow scripts to be fetched from that URL base.

**Comment by IvanExpert** [comment]
Sure; in addition, I'd suggest a command line parameter in a2server-setup for a URL or local file system path which could override the variable in the script.

**Comment by knghtbrd** [comment]
I've considered that and I like the idea.  I held off on that for the 
moment pending making a few things "more generic".

In that process I'd like to run a whitespace cleanup as well.  You 
appear to have changed editors at some point during development.  
Tabs, spaces, etc.  I'll make it all tabs if that's okay, and I'll 
just commit that straight to the main repository.  I should do that 
separately from other commits.

Joseph

**Comment by IvanExpert** [comment]
Sure thing. I'd ilke to stay with four-space indents in general, though there are a few places where I use two-space indents (e.g. intentional mid-line breaks). Why don't you clean up a file the way you think it should be and I'll diff it against the original to see if it all looks makes sense to me.

**Comment by knghtbrd** [comment]
vim used a full tab indent for mid-line breaks, but that's easily 
corrected.  The diff was pretty small, but the spacing is presently 
consistent.  Pretty pleased with that.

Joseph

**Comment by IvanExpert** [comment]
I'm all for consistency.
