### ISSUE TITLE
INFO: commands for making binary tarballs

### ISSUE THREAD

**Issue by IvanExpert** [RasppleII/a2server#12]
Binary tarballs are downloaded for faster installation that doesn't require installing development libraries or the compilation time.

These tarballs are Including but probably not limited to the below. Change _x86 to _rpi as appropriate.

sudo tar Pzcvf cftp-debian7_x86.tgz /usr/local/bin/cftp
sudo tar Pzcvf ttytter_readline-debian7_x86.tgz /usr/local/share/perl/5.14.2/Term/ReadLine/TTYtter.pm /usr/local/lib/perl/5.14.2/Term/ReadKey.pm
sudo tar Pzcvf kegs-debian7_x86.tgz /usr/local/bin/kegs /usr/local/bin/xkegs /usr/local/bin/kegs-setup /usr/local/bin/to_pro /usr/local/bin/partls /usr/local/lib/config.kegs
sudo tar Pzcvf linapple-debian7_x86.tgz /usr/local/bin/linapple /usr/local/linapple

The following is one long command:

tar Pzcvf netatalk224-debian7_x86.tgz /etc/netatalk /etc/default/netatalk /etc/init.d/netatalk /usr/local/sbin/a2boot /usr/local/sbin/cnid_metad /usr/local/sbin/cnid_dbd /usr/local/sbin/papd /usr/local/sbin/atalkd /usr/local/sbin/afpd /usr/local/share/man/man1 /usr/local/share/man/man1/netatalk-config.1 /usr/local/share/man/man1/papstatus.1 /usr/local/share/man/man1/macusers.1 /usr/local/share/man/man1/dbd.1 /usr/local/share/man/man1/pap.1 /usr/local/share/man/man1/afppasswd.1 /usr/local/share/man/man1/afpldaptest.1 /usr/local/share/man/man1/single2bin.1 /usr/local/share/man/man1/nbp.1 /usr/local/share/man/man1/nbplkup.1 /usr/local/share/man/man1/nbprgstr.1 /usr/local/share/man/man1/nbpunrgstr.1 /usr/local/share/man/man1/getzones.1 /usr/local/share/man/man1/asip-status.pl.1 /usr/local/share/man/man1/unhex.1 /usr/local/share/man/man1/unbin.1 /usr/local/share/man/man1/aecho.1 /usr/local/share/man/man1/hqx2bin.1 /usr/local/share/man/man1/unsingle.1 /usr/local/share/man/man1/ad.1 /usr/local/share/man/man1/macbinary.1 /usr/local/share/man/man1/psorder.1 /usr/local/share/man/man1/uniconv.1 /usr/local/share/man/man1/apple_dump.1 /usr/local/share/man/man1/megatron.1 /usr/local/share/man/man8 /usr/local/share/man/man8/timelord.8 /usr/local/share/man/man8/papd.8 /usr/local/share/man/man8/afpd.8 /usr/local/share/man/man8/psf.8 /usr/local/share/man/man8/cnid_dbd.8 /usr/local/share/man/man8/cnid_metad.8 /usr/local/share/man/man8/atalkd.8 /usr/local/share/man/man8/papstatus.8 /usr/local/share/man/man3 /usr/local/share/man/man3/nbp_name.3 /usr/local/share/man/man3/atalk_aton.3 /usr/local/share/man/man4 /usr/local/share/man/man4/atalk.4 /usr/local/share/man/man5 /usr/local/share/man/man5/afp_ldap.conf.5 /usr/local/share/man/man5/afp_signature.conf.5 /usr/local/share/man/man5/netatalk.conf.5 /usr/local/share/man/man5/afpd.conf.5 /usr/local/share/man/man5/papd.conf.5 /usr/local/share/man/man5/atalkd.conf.5 /usr/local/share/man/man5/afp_voluuid.conf.5 /usr/local/share/man/man5/AppleVolumes.system.5 /usr/local/share/man/man5/AppleVolumes.5 /usr/local/share/man/man5/AppleVolumes.default.5 /usr/local/share/netatalk /usr/local/share/netatalk/pagecount.ps /usr/local/share/aclocal /usr/local/share/aclocal/netatalk.m4 /usr/local/include/netatalk /usr/local/include/netatalk/aarp.h /usr/local/include/netatalk/at.h /usr/local/include/netatalk/phase2.h /usr/local/include/netatalk/ddp.h /usr/local/include/netatalk/endian.h /usr/local/include/netatalk/at_var.h /usr/local/include/netatalk/ddp_var.h /usr/local/include/atalk /usr/local/include/atalk/cnid.h /usr/local/include/atalk/zip.h /usr/local/include/atalk/vfs.h /usr/local/include/atalk/paths.h /usr/local/include/atalk/aep.h /usr/local/include/atalk/uam.h /usr/local/include/atalk/compat.h /usr/local/include/atalk/volume.h /usr/local/include/atalk/list.h /usr/local/include/atalk/asp.h /usr/local/include/atalk/rtmp.h /usr/local/include/atalk/adouble.h /usr/local/include/atalk/afp.h /usr/local/include/atalk/logger.h /usr/local/include/atalk/tdb.h /usr/local/include/atalk/atp.h /usr/local/include/atalk/unicode.h /usr/local/include/atalk/util.h /usr/local/include/atalk/ddp.h /usr/local/include/atalk/directory.h /usr/local/include/atalk/nbp.h /usr/local/include/atalk/pap.h /usr/local/include/atalk/server_child.h /usr/local/include/atalk/server_ipc.h /usr/local/include/atalk/volinfo.h /usr/local/include/atalk/uuid.h /usr/local/include/atalk/hash.h /usr/local/include/atalk/unix.h /usr/local/include/atalk/ea.h /usr/local/include/atalk/dsi.h /usr/local/include/atalk/netddp.h /usr/local/include/atalk/acl.h /usr/local/include/atalk/ldapconfig.h /usr/local/include/atalk/queue.h /usr/local/etc/netatalk /usr/local/etc/netatalk/uams /usr/local/etc/netatalk/uams/uams_clrtxt.so  /usr/local/etc/netatalk/uams/uams_dhx_passwd.so /usr/local/etc/netatalk/uams/uams_dhx2_passwd.so /usr/local/etc/netatalk/uams/uams_passwd.so /usr/local/etc/netatalk/uams/uams_passwd.a /usr/local/etc/netatalk/uams/uams_passwd.la /usr/local/etc/netatalk/uams/uams_randnum.a /usr/local/etc/netatalk/uams/uams_guest.a /usr/local/etc/netatalk/uams/uams_guest.so /usr/local/etc/netatalk/uams/uams_guest.la /usr/local/etc/netatalk/uams/uams_dhx.so /usr/local/etc/netatalk/uams/uams_dhx2.so /usr/local/etc/netatalk/uams/uams_randnum.la /usr/local/etc/netatalk/uams/uams_dhx_passwd.a /usr/local/etc/netatalk/uams/uams_dhx2_passwd.a /usr/local/etc/netatalk/uams/uams_dhx_passwd.la /usr/local/etc/netatalk/uams/uams_dhx2_passwd.la /usr/local/etc/netatalk/uams/uams_randnum.so /usr/local/etc/netatalk/papd.conf /usr/local/etc/netatalk/AppleVolumes.default /usr/local/etc/netatalk/afpd.conf /usr/local/etc/netatalk/AppleVolumes.system /usr/local/etc/netatalk/atalkd.conf /usr/local/libexec /usr/local/libexec/ifpap /usr/local/libexec/tfwmpap /usr/local/libexec/psa /usr/local/libexec/ifwpaprev /usr/local/libexec/ifwmpap /usr/local/libexec/ofpap /usr/local/libexec/etc2ps.sh /usr/local/libexec/ofmpap /usr/local/libexec/ifpaprev /usr/local/libexec/ofwpap /usr/local/libexec/ifmpaprev /usr/local/libexec/tfmpaprev /usr/local/libexec/tfwpap /usr/local/libexec/tfwpaprev /usr/local/libexec/ifwpap /usr/local/libexec/psf /usr/local/libexec/tfpaprev /usr/local/libexec/tfwmpaprev /usr/local/libexec/ifwmpaprev /usr/local/libexec/ofwmpap /usr/local/libexec/tfmpap /usr/local/libexec/ifmpap /usr/local/libexec/tfpap /usr/local/bin/unsingle /usr/local/bin/afppasswd /usr/local/bin/showppd /usr/local/bin/unbin /usr/local/bin/ad /usr/local/bin/hqx2bin /usr/local/bin/lp2pap.sh /usr/local/bin/netatalk-config /usr/local/bin/megatron /usr/local/bin/single2bin /usr/local/bin/dbd /usr/local/bin/unhex /usr/local/bin/add_netatalk_printer /usr/local/bin/pap /usr/local/bin/nbprgstr /usr/local/bin/getzones /usr/local/bin/nadheader /usr/local/bin/binheader /usr/local/bin/adv1tov2 /usr/local/bin/asip-status.pl /usr/local/bin/macusers /usr/local/bin/macbinary /usr/local/bin/nbplkup /usr/local/bin/afpldaptest /usr/local/bin/uniconv /usr/local/bin/psorder /usr/local/bin/apple_dump /usr/local/bin/aecho /usr/local/bin/papstatus /usr/local/bin/nbpunrgstr /usr/local/bin/cnid2_create /usr/local/lib/libatalk.a /usr/local/lib/libatalk.la

**Comment by knghtbrd** [comment]
We should move this info to the wiki

**Comment by knghtbrd** [comment]
Moved to wiki: https://github.com/RasppleII/a2server/wiki/Commands-for-making-binary-tarballs
