### ISSUE TITLE
A2SERVER: remove console setup step for Ubuntu (installer step 7)

### ISSUE THREAD

**Issue by IvanExpert** [RasppleII/a2server#13]
This is legacy cruft, and Ubuntu isn't the target any more, Debian is. This should probably be removed.

**Comment by knghtbrd** [comment]
I think I saw something about errors to the console that I've seen in 
Debian, so perhaps the script isn't totally cruft at this point.  Or 
perhaps its purpose should be altered a bit?

Joseph

**Comment by IvanExpert** [comment]
Yeah, it's possible that some of the stuff it does isn't Ubuntu-specific. I can't remember.

**Comment by knghtbrd** [comment]
Closed by 7cf972c (which didn't auto-close this for some reason.)
