### ISSUE TITLE
A2CLOUD: have ADTPro notice changes to disk image

### ISSUE THREAD

**Issue by IvanExpert** [RasppleII/a2server#19]
For speed, ADTPro now loads the disk image of a virtual disk into RAM rather than access the disk file each time out, and then flushes on writes (or might even do live writes as it used to do live reads). This causes issues if the disk image is modified outside of ADTPro. ADTPro should have a way of recognizing changes to the disk image it has in RAM. This is really an ADTPro issue, and has been submitted there:
http://sourceforge.net/p/adtpro/feature-requests/10/

**Comment by knghtbrd** [comment]
It's really hard to do this in Java.  If we ever were to replace the ADTPro server with something Linux-specific (at least when built for Linux) this is easily done.  But the best thing you can do in Java generally is to reread the whole file periodically to look for differences or keep reading the directory to see if the file's mod time changes.  That's a pain in the butt for sure!

**Comment by knghtbrd** [comment]
This issue was moved to RasppleII/a2cloud#11
