### ISSUE TITLE
Simplify Spectrum Deluxe installation

### ISSUE THREAD

**Issue by IvanExpert** [RasppleII/a2server#25]
Since Spectrum Deluxe 2.5.3 installation was added, Ewen put out a 2.5.4 release. I don't think there are new features -- I can't remember -- but in any event it's a ProDOS image, unlike the HFS image of 2.5.3, so it's probably a lot less convoluted to get and install the software than what I've got in there now. (On the other hand, it works, so maybe it's not worth fixing what ain't broke.)

**Comment by knghtbrd** [comment]
Ivan, do you consider this issue resolved by 1.2.5?

**Comment by IvanExpert** [comment]
Nope. It was on the list of things to address, but I didn't get to it.

I did, however, investigate needs doing, which I'll document here for when I or you or someone gets to it:

Either there needs to be a ReadMe.txt in the Spectrum folder, explaining that MountIt needs to be installed and then the images mounted with it, or:

make a working directory in tmp
- if there's no GS/OS installed (SYSTEM/START.GS.OS), then just download the disk images as it currently does
- install unzip (I think I actually snuck this in to a2server-2-tools.txt, and may or may not have forgotten to mention it, which means you may or may not have merged it in
- download http://www.speccie.co.uk/speccie/software/spectrum_gold_2mg.zip
- unzip it
- copy the file with dd, skipping the first 64 bytes, yielding spectrum_gold.hdv
- cppo -s -ad spectrum_gold.hdv 
- copy the following files and their ./.AppleDouble counterparts from the working directory/SPECTRUM.GOLD:

INSTALLER/EXTRAS/CDEVS -> $A2FILES/SYSTEM/CDEVS
INSTALLER/EXTRAS/TOOLS -> $A2FILES/SYSTEM/TOOLS
INSTALLER/EXTRAS/FONTS -> $A2FILES/SYSTEM/FONTS
INSTALLER/EXTRAS/SYSTEM.SETUP -> $A2FILES/SYSTEM/SYSTEM.SETUP
SPECTRUM.2.5.4 -> $A2FILES/COMM

Possibly also some of the Help files and stuff for the Apple Menu too, I'd need to figure out where that stuff is.

Ivan.

**Comment by knghtbrd** [comment]
I notice you are now unpacking the hdv image, so I thought you might 
have updated the version used as well.  Okay, I'll leave this open 
for now--I'm still working on the boot files installer, but I'm just 
about done with the substance of that.  I need some folks to test the 
ProDOS 8 patched files to make I applied the patches correctly and 
also to backport those patches to the existing shell installer.  
Otherwise that's done.

When my Uthernet II arrives, I can see about setting up Spectrum.  
The MacIP stuff seems like it will be cool, but I'd rather work with 
one unknown at a time.  If you haven't got a patch for that, I'll 
assign myself then.

Joseph

**Comment by IvanExpert** [comment]
> I notice you are now unpacking the hdv image, so I thought you might 
> have updated the version used as well.

Yeah, I've been poking at it. As of this morning, I'm no longer unpacking the HDV image, because the installer doesn't work when run from folders. What's in there now is partially complete, so it's functionally disabled for the moment, meaning the behavior at this minute is the same as 1.2.5.

> Okay, I'll leave this open 
> for now--I'm still working on the boot files installer, but I'm just 
> about done with the substance of that. I need some folks to test the 
> ProDOS 8 patched files to make I applied the patches correctly and 
> also to backport those patches to the existing shell installer. 
> Otherwise that's done.

See my other comment about ProDOS 8 patches.

> When my Uthernet II arrives, I can see about setting up Spectrum. 
> The MacIP stuff seems like it will be cool, but I'd rather work with 
> one unknown at a time. If you haven't got a patch for that, I'll 
> assign myself then.

Spectrum in and of itself is also still useful for plain old serial communcations for A2CLOUD, in addition to Uthernet or potentially Mac IP.

> Joseph
> 
> On Sun, Nov 15, 2015 at 02:02:11PM -0800, IvanExpert wrote:
> 
> > Nope. It was on the list of things to address, but I didn't get to it.
> > 
> > I did, however, investigate needs doing, which I'll document here for when I or you or someone gets to it:
> > 
> > Either there needs to be a ReadMe.txt in the Spectrum folder, explaining that MountIt needs to be installed and then the images mounted with it, or:
> > 
> > make a working directory in tmp
> > - if there's no GS/OS installed (SYSTEM/START.GS.OS), then just download the disk images as it currently does
> > - install unzip (I think I actually snuck this in to a2server-2-tools.txt, and may or may not have forgotten to mention it, which means you may or may not have merged it in
> > - download http://www.speccie.co.uk/speccie/software/spectrum_gold_2mg.zip
> > - unzip it
> > - copy the file with dd, skipping the first 64 bytes, yielding spectrum_gold.hdv
> > - cppo -s -ad spectrum_gold.hdv
> > - copy the following files and their ./.AppleDouble counterparts from the working directory/SPECTRUM.GOLD:
> > 
> > INSTALLER/EXTRAS/CDEVS -> $A2FILES/SYSTEM/CDEVS
> > INSTALLER/EXTRAS/TOOLS -> $A2FILES/SYSTEM/TOOLS
> > INSTALLER/EXTRAS/FONTS -> $A2FILES/SYSTEM/FONTS
> > INSTALLER/EXTRAS/SYSTEM.SETUP -> $A2FILES/SYSTEM/SYSTEM.SETUP
> > SPECTRUM.2.5.4 -> $A2FILES/COMM
> > 
> > Possibly also some of the Help files and stuff for the Apple Menu too, I'd need to figure out where that stuff is.
> > 
> > Ivan.
> >

**Comment by IvanExpert** [comment]
Full Spectrum install is now complete and live in the installer at http://ivanx.com/a2server/setup.

**Comment by knghtbrd** [comment]
On Sun, Nov 22, 2015 at 02:38:27PM -0800, IvanExpert wrote:

> Full Spectrum install is now complete and live in the installer at http://ivanx.com/a2server/setup.

Would you like me to merge that in?  That's starting to get a little 
more difficult because you've not been merging the other way.

**Comment by IvanExpert** [comment]
Could you? This is the last time I'm going to make any changes to what's directly at ivanx.com. Anything going forward I'll check out of Github first. If it's a pain for you, I am happy to do it myself.

I'm pretty sure the only thing that's different since the last merge is the chunk of code about Spectrum installation.

**Comment by knghtbrd** [comment]
It'd be a little easier if I had a diff of 1.2.5 to 1.2.6, since the 
scripts delete themselves upon being run.  (That's another reason to 
stop doing that.)  It shouldn't be too bad because there ought to be 
no other differences than the Spectrum stuff which is all in 
a2server-5-netboot.txt.

I'll take care of it tonight.

Joseph

**Comment by knghtbrd** [comment]
Would you say 8cfa6cb resolves this issue, or do you think more is still needed?

**Comment by IvanExpert** [comment]
Looks good!

**Comment by knghtbrd** [comment]
Cool, another issue marked resolved!
