### ISSUE TITLE
ER: Amper-Term

### ISSUE THREAD

**Issue by IvanExpert** [RasppleII/a2server#26]
This is probably my most wished-for enhancement. Create a BASIC.SYSTEM utility called Amper-Term
which would allow you to send single Bash instructions, and get responses, from AppleSoft, e.g. "&vsd2 loderunner.dsk", "&ls", etc, rather than requiring a comm program to formally log into the shell and leave what you're doing. A GS/OS CDA would be phenomenal as well, as it would allow you to quickly change disks in the virtual drives, or even grab stuff off the internet via "&wget" or what have you.

**Comment by knghtbrd** [comment]
This issue was moved to RasppleII/a2cloud#9
