### ISSUE TITLE
update supported OS warnings on A2SERVER install

### ISSUE THREAD

**Issue by IvanExpert** [RasppleII/a2server#27]
A2SERVER (and maybe A2CLOUD) dutifully checks to see if it knows about what verson of Debian or Raspbian you're about to install on and warns you if it doesn't. I have no idea if it's up to date or even overkill.

**Comment by knghtbrd** [comment]
My gut says overkill for A2SERVER now that kernel fiddling isn't necessary.  Probably better to determine whether your kernel has DDP support.  Not 100% on how to do that.

**Comment by IvanExpert** [comment]
probably something along the lines of "modprobe appletalk" and see whether it's in lsmod after that.

**Comment by pneubauer** [comment]
AppleTalk could be built into the kernel rather than a module, so the "lsmod" check could miss support.  How about a short program that tries to create a DDP socket?  If socket creation succeeds, then the kernel must support DDP.

See http://man7.org/linux/man-pages/man7/ddp.7.html.

**Comment by knghtbrd** [comment]
If there isn't already one, I suppose we could add a tool to test for 
ddp support in our netatalk distribution?

Joseph

**Comment by knghtbrd** [comment]
FWIW I did commit 9de61e5 which is the temporary fix to this problem.  Leaving the issue open until it's properly addressed, however.

**Comment by knghtbrd** [comment]
I think we've got this one covered now, by b5496b5 if not by earlier 9de61e5.
