### ISSUE TITLE
no login; menu on startup instead of command summary after login

### ISSUE THREAD

**Issue by IvanExpert** [RasppleII/a2server#28]
Something to consider -- automatic login (like Raspbian has on first boot), which then throws you into a menu to do common stuff, rather than getting the screen full of text telling you what to type after you log in now.

**Comment by knghtbrd** [comment]
Automatic login is something that is quite easy to do under jessie.  It's possible under wheezy, but it's a little more hacky.

Menu's a good thing to consider though.

**Comment by knghtbrd** [comment]
This issue was moved to RasppleII/a2cloud#8
