### ISSUE TITLE
Info: UDEV

### ISSUE THREAD

**Issue by IvanExpert** [RasppleII/a2server#29]
How to observe UDEV events
sudo udevadm monitor --environment --udev

How to re-scan udev after changing rules:
sudo udevadm trigger --action=change

**Comment by knghtbrd** [comment]
Useful for debugging the current A2CLOUD serial setup.  Ideally though I want to be able to show you all of the serial ports we can find on your machine, and help you figure out which one to use for what.  That's important if you want to be able to use Apple 2 Pi and you don't have a LVTTL level shifter or want to use multi-serial USB adapters.  There are x2 and x4 adapters made by Keyspan that would be ideal, and there are others besides if you go looking.

Plus, anyone using a newer Pi is going to have more than two USB ports, and most of us have got hubs connected anyway.  The upper/lower port thing doesn't scale, and when it doesn't work out of the box it's incredibly frustrating to figure out why it isn't working.

Still working on better solutions for that.  Need a few more serial adapters myself for testing.

**Comment by knghtbrd** [comment]
Issue belongs in A2CLOUD's wiki.

**Comment by knghtbrd** [comment]
Moved to wiki: https://github.com/RasppleII/a2server/wiki/udev-commands-for-developers
