### ISSUE TITLE
License terms unclear

### ISSUE THREAD

**Issue by knghtbrd** [RasppleII/a2server#3]
(For completeness)

[Former Debian developer hat ON] A2SERVER has no specified license, which effectively renders distribution terms to be a restrictive "All Rights Reserved". This prohibits redistribution, open development, collaboration, and GitHub's fork-modify-push-pull development model and is incompatible with the Debian DFSG, OSI Open Source Definition, blah blah blah…

[Former Debian developer hat OFF] Yeah, it's a s set of shell scripts bodied together over time to install netatalk, image utilities, and a few glue scripts, big deal. "Don't take my name off it, don't pretend you're me, and don't be an ass" seems appropriate, but meh. I'd suggest throwing current Creative Commons at it and call it good, but that's @IvanExpert's decision.I'd encourage something Debian-friendly so that these may become part of a Debian package someday.

**Comment by IvanExpert** [comment]
Granted, it's not the most intuitive or comprehensive place for it, but I specified the license terms (WTFPL) at the bottom of here: http://ivanx.com/appleii/a2server/a2server_features.html . Though I also like "Don't take my name off it, don't pretend you're me, and don't be an ass." I'll take a look at the CC licenses to see if anything seems appropriate. I have no idea what's considered Debian-friendly or not.

**Comment by knghtbrd** [comment]
Debian Free Software Guidelines are the bottom half of their social 
contract page: https://www.debian.org/social_contract

I like the CC licenses because they figured out how to balance the 
legalese with the human-readable element—they provide both.  :)

Joseph

**Comment by knghtbrd** [comment]
BTW Ivan have you thought any more about this?  I can and should go add the WTFPL, but have held back pending you considering alternatives since I mentioned them.  :)

**Comment by IvanExpert** [comment]
I haven't; I will.

**Comment by knghtbrd** [comment]
Status update: We're using CC stuff elsewhere now, as permissive as possible for the content in question.  Shell scripts will probably be CC-BY or CC-Zero.

**Comment by knghtbrd** [comment]
I believe 0fffaf9 resolved this issue to the extent necessary.
