### ISSUE TITLE
A2CLOUD: support SLIP or PPP for Marinetti

### ISSUE THREAD

**Issue by IvanExpert** [RasppleII/a2server#35]
I looked into this and once got it cooking with SLIrP, but SLIrP is super slow, and I could never get the right script going. The bigger problem is that the lack of conditional logic in Marinetti's scripting makes it impossible to determine whether the serial shell is in any of three states: logged out, logged in, logged in with SLIP (or PPP) running.

I also suspect that even with proper SLIP or PPP server running on the Pi, it would still be just too slow; I'm not even sure that GS/OS can keep up with the theoretically 57,600 available.

**Comment by knghtbrd** [comment]
This issue was moved to RasppleII/a2cloud#3
