### ISSUE TITLE
A2CLOUD: Consider supporting Ewen's old comm programs

### ISSUE THREAD

**Issue by IvanExpert** [RasppleII/a2server#36]
Ewen recently re-released a couple of 8-bit comm programs he write long ago, one for ProDOS and one for DOS 3.3. The DOS 3.3 one is especially interesting since it almost certainly won't require an enhanced //e, which ProTERM and Z-Link do. And some people just like DOS 3.3 better.

**Comment by knghtbrd** [comment]
This issue was moved to RasppleII/a2cloud#4
