### ISSUE TITLE
Should not unconditionally nuke ~/GNUStep

### ISSUE THREAD

**Issue by knghtbrd** [RasppleII/a2server#53]
The GNUStep dir in ~ is the equivalent of ~/Like Barry on a Mac if you have GNUStep apps installed. You may not, or even probably don't, but we shouldn't go nuking the dir in case you do.

**Comment by IvanExpert** [comment]
I agree. Will be removed in next commit.

**Comment by IvanExpert** [comment]
Fixed as of 1.2.8; you can close.

**Comment by knghtbrd** [comment]
Cool thing: If you know the bug number, you can just add "closes #53" to the commit log for that bug and GitHub will do the right thing when you push changes out.  :)
