### ISSUE TITLE
Support Jessie

### ISSUE THREAD

**Issue by IvanExpert** [RasppleII/a2server#6]
Raspple II should support Jessie, as Wheezy is a dead end. Unfortunately, systemd is going to make that real work, especially for A2CLOUD.

Some known issues from Feb-15 Jessie port for RPi2B at:
http://sjoerd.luon.net/posts/2015/02/debian-jessie-on-rpi2/

/etc/network/interfaces needed to have eth0 added
no g++4.6, so no LinApple
no GSport (needs -march=armv7; and then, //lib/arm-linux-gnueabihf/libdl.so.2: error adding symbols: DSO missing from command line)
no Kegs (needs -march=armv7; and even then there's no /dev/dsp so won't launch)

in addition to known issues on Debian i386 8.0.0:
LXDE has been changed and menu groups are no longer present
ADTPro doesn't work (no RXTX lib, or it doesn't work, or something)
LXDE screensaver turns on

installing gcc/g++ 4.6 so we can build linapple on Jessie:
sudo apt-get install build-essential
mkdir /tmp/a2cloud-install/gcc-4.6
cd /tmp/a2cloud-install/gcc-4.6
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-4.6/gcc-4.6_4.6.3-14_i386.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-4.6/gcc-4.6-base_4.6.3-14_i386.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-4.6/cpp-4.6_4.6.3-14_i386.deb
wget http://ftp.us.debian.org/debian/pool/main/m/mpclib/libmpc2_0.9-4_i386.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-4.6/g++-4.6_4.6.3-14_i386.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-4.6/libstdc++6-4.6-dev_4.6.3-14_i386.deb
sudo dpkg -i *
cd /tmp/a2cloud-install
rm -r gcc-4.6

issues/conflicts after a2cloud+a2server install:
/etc/skel/.bashrc (ok to replace with new)
services need restarting
bash.bashrc:
-source /usr/local/etc/a2server-aliases
-source /usr/local/etc/a2cloudrc
(sudo telinit q)? (sudo init q?)

Would like easy upgrade from existing Wheezy Raspbian install? (e.g. a2cloud-update os)

Would like easy upgrade from existing Debian 7 install? (e.g. a2cloud-update os)

any Apple II Pi issues? (Dave's problem, but as long as it's part of Raspple II and installed by A2CLOUD...)

**Comment by knghtbrd** [comment]
Jessie support for A2SERVER at least is resolved as of b5496b5.  A2CLOUD is not yet fixed, but if there isn't a Jessie issue for A2CLOUD, it belongs there not here.
