### ISSUE TITLE
provide amd64 binaries (in addition to armv6 and i386)

### ISSUE THREAD

**Issue by IvanExpert** [RasppleII/a2server#9]
Ideally, the A2SERVER and A2CLOUD install scripts don't have to compile any source from scratch when installed on common platforms (currently defined as Debian Wheezy i386, and Raspbian Wheezy ARMv6). It would make sense to also provide Debian x64 binaries, as well as any Jessie binaries when that comes to pass.

**Comment by IvanExpert** [comment]
This is done as of 1.2.8 (support is in; the binaries themselves aren't hosted anywhere yet, but they will be when 1.5.0 is released, and they can be downloaded now for developers self or locally hosting).

**Comment by knghtbrd** [comment]
I'm okay with closing this issue the support is there at least.  Having the binaries there isn't as necessary on amd64 since if you've got an amd64 at least you'll have enough CPU power to compile things this century if necessary.  Feel free to close if you agree, or I can.

**Comment by IvanExpert** [comment]
Perhaps not as necessary in that it won't take forever and ever if they're not available, but if binaries are available it still prevents end users from having to install build-essential and everything that goes with it when running the install script. In any event, closing.
